### PR TITLE
Add function-based patterns and improve code organization

### LINKED ISSUE #58: Allow pattern functions
For advanced use-cases it would be great if `pattern` could also be a function, that returns the matches.

Then I could write code analysing the string or use advanced patterns with [LPeg](https://www.inf.puc-rio.br/~roberto/lpeg/) for example.

If this is something you could consider for other.nvim, I am open to provide a PR @rgroli

### PR DESCRIPTION
**Pull request by b0o**
This PR adds support for function-based patterns while improving the overall organization of the code. While I apologize for the large diff, these changes help support the new pattern functionality.

- Added function-based patterns in mappings
  - Functions should return a table containing one or more captures, or nil for no match
  - Added docs and tests for function-based patterns
- Refactored state management to be more explicit
- Added type annotations
- Improved error handling around option access
- Added fallback values for configuration
- Better organization of utility functions

All existing functionality should remain unchanged and all tests are passing, except for the livewire test that I've commented out. That test was failing before any of my modifications, and I wasn't able to figure out exactly why.

Fixes #58

### CODE REVIEW

**Comment by rgroli** [comment]
Wow, that's quite the PR—thanks a ton for putting in the effort! 🙌 I'll run a few tests, and as long as everything checks out, I'll go ahead and merge it. 😊

**Comment by rgroli** [comment]
Thanks again, really great pr - very much appreciated! Really nice refactoring and implementation! 🚀

**Comment by rgroli** [comment]
Since your Lua skills clearly surpass mine, I’ve sent you an invite to collaborate on the repo. 😄

**Comment by b0o** [comment]
Awesome, thanks for merging! I will keep my eye on the issues to see if the changes broke anyone’s workflow and try to fix them if so.

**Pull request merged**
